apiVersion: v1
kind: ConfigMap
metadata:
  name: kiali-nginx-conf
  namespace: istio-system
data:
  default.conf: |
    server {
      listen 8080;

      location / {
        auth_basic "Kiali";
        auth_basic_user_file /etc/nginx/auth/auth;

        proxy_pass http://kiali:20001;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $remote_addr;
      }
    }

